### ISSUE TITLE
Set Signature Hash Algo with CLI

### ISSUE THREAD

**Issue by kingcdavid** [globalsign/hvclient#29]
There is currently no option to set the signature hash algo from the CLI, i.e.

First generate a private key:
`openssl genrsa -out ./private.key 2048`

Then use hvclient to create a CSR:

`./hvclient -privatekey ./private.key --commonname example.com -csrout csr.pem > csr.pem`

We can then try to issue a cert

`./hvclient --commonname example.com -dnsnames example.com -csr csr.pem
hvclient: couldn't obtain certificate: 422: signature.hash_algorithm: is required`

But the account is configured to require signature.hash_algorithm but that isn't an option to set in the CLI

either it should allow the client  to set it, or have a sensible default

**Comment by nhgs64** [comment]
I'm also running into this issue for a devops project, can we have this field added please? @yateeshbhardwaj94

**Comment by yateeshbhardwaj94** [comment]
@nhgs64 Yeah sure we can discuss but what I know is that during creation of template on Atlas for API credentials, you can set your HASH algorithm there only.

**Comment by iamantil** [comment]
I have tried from RSA to ECC and didn't receive the hash algorithm error but getting another error: use ParsePKCS8PrivateKey instead for this key format.

**Comment by toddgaunt-gs** [comment]
I've opened and will be merging #77 to address this.

**Comment by toddgaunt-gs** [comment]
Closed by https://github.com/globalsign/hvclient/pull/30

**Comment by toddgaunt-gs** [comment]
Closed by https://github.com/globalsign/hvclient/pull/30
